### ISSUE TITLE
Would appreciate if you could give any pointers. facing a similar problem like the app you made.

### ISSUE THREAD

**Issue by SaudTauqeer** [Stefie/aframe-curvedimage-calculator#1]
Hi, I am facing a similar issue and while searching for the solution I came across your app. 
I would super appreciate if you could give me some pointers on how can I fix my problem.
Here's a link to my issue: https://stackoverflow.com/questions/58461077/calculate-height-radius-and-theta-length-relative-to-the-image-aspect-ratio-in

**Comment by Stefie** [comment]
Hey! Phew, It's been like 2/1/2 years ago since I last looked at this code...
Looking at your Stackoverflow issue and your code, I'd say that part of your problem is your camera  position. Is there a reason why you're moving out 15 units on the z-axis and not just move your artboard 15 units instead?

The curvedimage component is derived from the cylinder primitive where every point has the same distance from a specified viewpoint. So instead of positioning a plane with x and y values,  you're projecting your image on a cylinder which is positioned in the room around a certain point with the radius.

I'd try to use `0 5 0` as your centerpoint/ camera position instead of `0 5 15` and move your elements out instead. Then you should use the x position of your flat images as the radius of your curvedimages.

I hope that helps a little. Have a good day!

**Comment by SaudTauqeer** [comment]
Thank you
